# Generated by Django 4.2.7 on 2023-11-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='School name')),
                ('course', models.CharField(max_length=200, verbose_name='Course name')),
                ('duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Course duration')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Certificate date')),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
