# Generated by Django 4.2.7 on 2023-11-10 11:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project name')),
                ('description', tinymce.models.HTMLField(max_length=5000, verbose_name='Project description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date finished')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Github link')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projectinformation')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
            },
        ),
    ]
